name: Android CI - Build APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Ensure placeholder files for Capacitor/Cordova
        run: |
          mkdir -p android/capacitor-cordova-android-plugins
          echo "// placeholder" > android/capacitor-cordova-android-plugins/cordova.variables.gradle

      - name: Build APK
        working-directory: android
        run: |
          chmod +x ./gradlew
          ./gradlew --no-daemon assembleRelease

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: wikirol-apk
          path: android/app/build/outputs/apk/release/*.apk
